{
 "title": "ACE_Crypto",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "crypto",
    "label": "Crypto",
    "query": {
     "query": "crypto_currency_circulating_supply{}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "MARKET CAP",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "crypto_currency_market_cap{name=\"$crypto\"}"
    }
   ]
  },
  {
   "title": "CIRCULATING SUPPLY",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Coins" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "crypto_currency_circulating_supply{name=\"$crypto\"}"
    }
   ]
  },
  {
   "title": "TOTAL SUPPLY",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Coins" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "crypto_currency_total_supply{name=\"$crypto\"}"
    }
   ]
  },
  {
   "title": "SUPPLY RATIO",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "crypto_currency_circulating_supply{name=\"$crypto\"}/crypto_currency_max_supply{name=\"$crypto\"}"
    }
   ]
  },
  {
   "title": "CHANGE OVER 1h",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "crypto_currency_price_change_percentage{name=\"$crypto\",duration=\"1h\"}"
    }
   ]
  },
  {
   "title": "CHANGE OVER 24h",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "crypto_currency_price_change_percentage{name=\"$crypto\",duration=\"24h\"}"
    }
   ]
  },
  {
   "title": "CHANGE OVER 7h",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "crypto_currency_price_change_percentage{name=\"$crypto\",duration=\"7d\"}"
    }
   ]
  },
  {
   "title": "PRICE / COIN",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "crypto_currency_price{name=\"$crypto\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "VOLUME - 24h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "crypto_currency_volume_24h{name=\"$crypto\"}",
     "legendFormat": " "
    }
   ]
  }
 ]
}