version: "3.9"

volumes:
    prometheus_data: {}
    grafana_data: {}

networks:
  front-tier: {}
  back-tier: {}

services:
  ace:
    container_name: ace
    image: stevencyb/alternative-crypto-exporter:latest
    restart: always
    environment:
      "log-level": 4
      "listen": ":8080"
      "quotes": "USD"
      "watch": "btc,eth,ltc"
    networks:
      - back-tier
    ports:
      - 8080:8080
  prometheus:
    image: prom/prometheus:v2.31.1
    volumes:
      - ./:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/etc/prometheus/prometheus_data/'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    depends_on:
      - ace
    ports:
      - 9090:9090
    networks:
      - back-tier
    restart: always
  grafana:
    image: grafana/grafana
    user: "472"
    depends_on:
      - prometheus
    ports:
      - 8081:3000
    volumes:
      - ./grafana_data:/var/lib/grafana
      - ./grafana_provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./config.monitoring
    networks:
      - back-tier
      - front-tier
    restart: always