# my global config
global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels: {}

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
         - targets: ['localhost:9090']
  - job_name: 'ace'
    scrape_interval: 5s
    static_configs:
         - targets: ['192.168.2.108:8080']
